package com.zedler.entity;
// Generated Aug 12, 2017 12:37:35 PM by Hibernate Tools 4.3.1



/**
 * FollowshipId generated by hbm2java
 */
public class FollowshipId  implements java.io.Serializable {


     private int userTo;
     private int userFrom;

    public FollowshipId() {
    }

    public FollowshipId(int userTo, int userFrom) {
       this.userTo = userTo;
       this.userFrom = userFrom;
    }
   
    public int getUserTo() {
        return this.userTo;
    }
    
    public void setUserTo(int userTo) {
        this.userTo = userTo;
    }
    public int getUserFrom() {
        return this.userFrom;
    }
    
    public void setUserFrom(int userFrom) {
        this.userFrom = userFrom;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FollowshipId) ) return false;
		 FollowshipId castOther = ( FollowshipId ) other; 
         
		 return (this.getUserTo()==castOther.getUserTo())
 && (this.getUserFrom()==castOther.getUserFrom());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserTo();
         result = 37 * result + this.getUserFrom();
         return result;
   }   


}


