package com.zedler.entity;
// Generated Aug 12, 2017 12:37:35 PM by Hibernate Tools 4.3.1



/**
 * Followship generated by hbm2java
 */
public class Followship  implements java.io.Serializable {


     private FollowshipId id;
     private User userByUserFrom;
     private User userByUserTo;
     private boolean following;

    public Followship() {
    }

    public Followship(FollowshipId id, User userByUserFrom, User userByUserTo, boolean following) {
       this.id = id;
       this.userByUserFrom = userByUserFrom;
       this.userByUserTo = userByUserTo;
       this.following = following;
    }
   
    public FollowshipId getId() {
        return this.id;
    }
    
    public void setId(FollowshipId id) {
        this.id = id;
    }
    public User getUserByUserFrom() {
        return this.userByUserFrom;
    }
    
    public void setUserByUserFrom(User userByUserFrom) {
        this.userByUserFrom = userByUserFrom;
    }
    public User getUserByUserTo() {
        return this.userByUserTo;
    }
    
    public void setUserByUserTo(User userByUserTo) {
        this.userByUserTo = userByUserTo;
    }
    public boolean isFollowing() {
        return this.following;
    }
    
    public void setFollowing(boolean following) {
        this.following = following;
    }




}


