package com.zedler.entity;
// Generated Aug 12, 2017 12:37:35 PM by Hibernate Tools 4.3.1



/**
 * FollowingsettingscontrolId generated by hbm2java
 */
public class FollowingsettingscontrolId  implements java.io.Serializable,Entity {


     private int userFrom;
     private int userTo;

    public FollowingsettingscontrolId() {
    }

    public FollowingsettingscontrolId(int userFrom, int userTo) {
       this.userFrom = userFrom;
       this.userTo = userTo;
    }
   
    public int getUserFrom() {
        return this.userFrom;
    }
    
    public void setUserFrom(int userFrom) {
        this.userFrom = userFrom;
    }
    public int getUserTo() {
        return this.userTo;
    }
    
    public void setUserTo(int userTo) {
        this.userTo = userTo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FollowingsettingscontrolId) ) return false;
		 FollowingsettingscontrolId castOther = ( FollowingsettingscontrolId ) other; 
         
		 return (this.getUserFrom()==castOther.getUserFrom())
 && (this.getUserTo()==castOther.getUserTo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserFrom();
         result = 37 * result + this.getUserTo();
         return result;
   }   


}


