package com.zedler.entity;
// Generated Aug 12, 2017 12:37:35 PM by Hibernate Tools 4.3.1



/**
 * Followingsettingscontrol generated by hbm2java
 */
public class Followingsettingscontrol  implements java.io.Serializable,Entity {


     private FollowingsettingscontrolId id;
     private boolean notification;

    public Followingsettingscontrol() {
    }

    public Followingsettingscontrol(FollowingsettingscontrolId id, boolean notification) {
       this.id = id;
       this.notification = notification;
    }
   
    public FollowingsettingscontrolId getId() {
        return this.id;
    }
    
    public void setId(FollowingsettingscontrolId id) {
        this.id = id;
    }
    public boolean isNotification() {
        return this.notification;
    }
    
    public void setNotification(boolean notification) {
        this.notification = notification;
    }




}


