package com.zedler.entity;
// Generated Aug 12, 2017 12:37:35 PM by Hibernate Tools 4.3.1



/**
 * Settingscontrol generated by hbm2java
 */
public class Settingscontrol  implements java.io.Serializable,Entity {


     private SettingscontrolId id;
//     private User userByUserTo;
//     private User userByUserFrom;
     private boolean scGps;
     private boolean scStatus;

    public Settingscontrol() {
    }

    public Settingscontrol(SettingscontrolId id, User userByUserTo, User userByUserFrom, boolean scGps, boolean scStatus) {
       this.id = id;
//       this.userByUserTo = userByUserTo;
//       this.userByUserFrom = userByUserFrom;
       this.scGps = scGps;
       this.scStatus = scStatus;
    }
   
    public SettingscontrolId getId() {
        return this.id;
    }
    
    public void setId(SettingscontrolId id) {
        this.id = id;
    }
//    public User getUserByUserTo() {
//        return this.userByUserTo;
//    }
//    
//    public void setUserByUserTo(User userByUserTo) {
//        this.userByUserTo = userByUserTo;
//    }
//    public User getUserByUserFrom() {
//        return this.userByUserFrom;
//    }
//    
//    public void setUserByUserFrom(User userByUserFrom) {
//        this.userByUserFrom = userByUserFrom;
//    }
    public boolean isScGps() {
        return this.scGps;
    }
    
    public void setScGps(boolean scGps) {
        this.scGps = scGps;
    }
    public boolean isScStatus() {
        return this.scStatus;
    }
    
    public void setScStatus(boolean scStatus) {
        this.scStatus = scStatus;
    }




}


